
    const fs = require('fs');
    export const chaptersData = {
  "Class 12": {
    "Physics": [
      { id: 'c1', title: 'Electric Charges and Fields' },
      { id: 'c2', title: 'Electrostatic Potential and Capacitance' },
      { id: 'c3', title: 'Current Electricity' },
      { id: 'c4', title: 'Moving Charges and Magnetism' },
      { id: 'c5', title: 'Magnetism and Matter' },
      { id: 'c6', title: 'Electromagnetic Induction' },
      { id: 'c7', title: 'Alternating Current' },
      { id: 'c8', title: 'Electromagnetic Waves' },
      { id: 'c9', title: 'Ray Optics and Optical Instruments' },
      { id: 'c10', title: 'Wave Optics' },
      { id: 'c11', title: 'Dual Nature of Radiation and Matter' },
      { id: 'c12', title: 'Atoms' },
      { id: 'c13', title: 'Nuclei' },
      { id: 'c14', title: 'Semiconductor Electronics' },
      { id: 'c15', title: 'Communication Systems' }
    ],
    "Maths": [
      { id: 'c1', title: 'Relations and Functions' },
      { id: 'c2', title: 'Inverse Trigonometric Functions' },
      { id: 'c3', title: 'Matrices' },
      { id: 'c4', title: 'Determinants' },
      { id: 'c5', title: 'Continuity and Differentiability' },
      { id: 'c6', title: 'Application of Derivatives' },
      { id: 'c7', title: 'Integrals' },
      { id: 'c8', title: 'Application of Integrals' },
      { id: 'c9', title: 'Differential Equations' },
      { id: 'c10', title: 'Vector Algebra' },
      { id: 'c11', title: 'Three Dimensional Geometry' },
      { id: 'c12', title: 'Linear Programming' },
      { id: 'c13', title: 'Probability' }
    ],
    "Chemistry": [
      { id: 'c1', title: 'The Solid State' },
      { id: 'c2', title: 'Solutions' },
      { id: 'c3', title: 'Electrochemistry' },
      { id: 'c4', title: 'Chemical Kinetics' },
      { id: 'c5', title: 'Surface Chemistry' },
      { id: 'c6', title: 'General Principles and Processes of Isolation of Elements' },
      { id: 'c7', title: 'The p-Block Elements' },
      { id: 'c8', title: 'The d- and f-Block Elements' },
      { id: 'c9', title: 'Coordination Compounds' },
      { id: 'c10', title: 'Haloalkanes and Haloarenes' },
      { id: 'c11', title: 'Alcohols, Phenols and Ethers' },
      { id: 'c12', title: 'Aldehydes, Ketones and Carboxylic Acids' },
      { id: 'c13', title: 'Amines' },
      { id: 'c14', title: 'Biomolecules' },
      { id: 'c15', title: 'Polymers' },
      { id: 'c16', title: 'Chemistry in Everyday Life' }
    ],
    "Biology": [
      { id: 'c1', title: 'Reproduction in Organisms' },
      { id: 'c2', title: 'Sexual Reproduction in Flowering Plants' },
      { id: 'c3', title: 'Human Reproduction' },
      { id: 'c4', title: 'Reproductive Health' },
      { id: 'c5', title: 'Principles of Inheritance and Variation' },
      { id: 'c6', title: 'Molecular Basis of Inheritance' },
      { id: 'c7', title: 'Evolution' },
      { id: 'c8', title: 'Human Health and Disease' },
      { id: 'c9', title: 'Strategies for Enhancement in Food Production' },
      { id: 'c10', title: 'Microbes in Human Welfare' },
      { id: 'c11', title: 'Biotechnology: Principles and Processes' },
      { id: 'c12', title: 'Biotechnology and its Applications' },
      { id: 'c13', title: 'Organisms and Populations' },
      { id: 'c14', title: 'Ecosystem' },
      { id: 'c15', title: 'Biodiversity and Conservation' },
      { id: 'c16', title: 'Environmental Issues' }
    ],
    "English": [
      { id: 'c1', title: 'The Last Lesson' },
      { id: 'c2', title: 'Lost Spring' },
      { id: 'c3', title: 'Deep Water' },
      { id: 'c4', title: 'The Rattrap' },
      { id: 'c5', title: 'Indigo' },
      { id: 'c6', title: 'Poets and Pancakes' },
      { id: 'c7', title: 'The Interview' },
      { id: 'c8', title: 'Going Places' },
      { id: 'c9', title: 'My Mother at Sixty-six' },
      { id: 'c10', title: 'An Elementary School Classroom in a Slum' },
      { id: 'c11', title: 'Keeping Quiet' },
      { id: 'c12', title: 'A Thing of Beauty' }
    ],
    "Business Studies": [
      { id: 'c1', title: 'Nature and Significance of Management' },
      { id: 'c2', title: 'Principles of Management' },
      { id: 'c3', title: 'Business Environment' },
      { id: 'c4', title: 'Planning' },
      { id: 'c5', title: 'Organising' },
      { id: 'c6', title: 'Staffing' },
      { id: 'c7', title: 'Directing' },
      { id: 'c8', title: 'Controlling' },
      { id: 'c9', title: 'Financial Management' },
      { id: 'c10', title: 'Financial Markets' },
      { id: 'c11', title: 'Marketing' },
      { id: 'c12', title: 'Consumer Protection' }
    ],
    "Economics": [
      { id: 'c1', title: 'Introduction to Microeconomics' },
      { id: 'c2', title: 'Theory of Consumer Behaviour' },
      { id: 'c3', title: 'Production and Costs' },
      { id: 'c4', title: 'The Theory of the Firm under Perfect Competition' },
      { id: 'c5', title: 'Market Equilibrium' },
      { id: 'c6', title: 'Non-Competitive Markets' },
      { id: 'c7', title: 'Introduction to Macroeconomics' },
      { id: 'c8', title: 'National Income Accounting' },
      { id: 'c9', title: 'Money and Banking' },
      { id: 'c10', title: 'Income Determination' },
      { id: 'c11', title: 'The Government Budget and the Economy' },
      { id: 'c12', title: 'Open Economy Macroeconomics' }
    ],
    "Accountancy": [
      { id: 'c1', title: 'Accountancy Chapter 1' },
      { id: 'c2', title: 'Accountancy Chapter 2' },
      { id: 'c3', title: 'Accountancy Chapter 3' },
      { id: 'c4', title: 'Accountancy Chapter 4' },
      { id: 'c5', title: 'Accountancy Chapter 5' },
      { id: 'c6', title: 'Accountancy Chapter 6' },
      { id: 'c7', title: 'Accountancy Chapter 7' },
      { id: 'c8', title: 'Accountancy Chapter 8' },
      { id: 'c9', title: 'Accountancy Chapter 9' },
      { id: 'c10', title: 'Accountancy Chapter 10' }
    ],
    "History": [
      { id: 'c1', title: 'History Chapter 1' },
      { id: 'c2', title: 'History Chapter 2' },
      { id: 'c3', title: 'History Chapter 3' },
      { id: 'c4', title: 'History Chapter 4' },
      { id: 'c5', title: 'History Chapter 5' },
      { id: 'c6', title: 'History Chapter 6' },
      { id: 'c7', title: 'History Chapter 7' },
      { id: 'c8', title: 'History Chapter 8' },
      { id: 'c9', title: 'History Chapter 9' },
      { id: 'c10', title: 'History Chapter 10' },
      { id: 'c11', title: 'History Chapter 11' },
      { id: 'c12', title: 'History Chapter 12' },
      { id: 'c13', title: 'History Chapter 13' },
      { id: 'c14', title: 'History Chapter 14' },
      { id: 'c15', title: 'History Chapter 15' }
    ],
    "Geography": [
      { id: 'c1', title: 'Geography Chapter 1' },
      { id: 'c2', title: 'Geography Chapter 2' },
      { id: 'c3', title: 'Geography Chapter 3' },
      { id: 'c4', title: 'Geography Chapter 4' },
      { id: 'c5', title: 'Geography Chapter 5' },
      { id: 'c6', title: 'Geography Chapter 6' },
      { id: 'c7', title: 'Geography Chapter 7' },
      { id: 'c8', title: 'Geography Chapter 8' },
      { id: 'c9', title: 'Geography Chapter 9' },
      { id: 'c10', title: 'Geography Chapter 10' }
    ],
    "Political Science": [
      { id: 'c1', title: 'Political Science Chapter 1' },
      { id: 'c2', title: 'Political Science Chapter 2' },
      { id: 'c3', title: 'Political Science Chapter 3' },
      { id: 'c4', title: 'Political Science Chapter 4' },
      { id: 'c5', title: 'Political Science Chapter 5' },
      { id: 'c6', title: 'Political Science Chapter 6' },
      { id: 'c7', title: 'Political Science Chapter 7' },
      { id: 'c8', title: 'Political Science Chapter 8' },
      { id: 'c9', title: 'Political Science Chapter 9' }
    ]
  },
  "Class 11": {
    "Physics": [
      { id: 'c1', title: 'Physical World' },
      { id: 'c2', title: 'Units and Measurements' },
      { id: 'c3', title: 'Motion in a Straight Line' },
      { id: 'c4', title: 'Motion in a Plane' },
      { id: 'c5', title: 'Laws of Motion' },
      { id: 'c6', title: 'Work, Energy and Power' },
      { id: 'c7', title: 'System of Particles and Rotational Motion' },
      { id: 'c8', title: 'Gravitation' },
      { id: 'c9', title: 'Mechanical Properties of Solids' },
      { id: 'c10', title: 'Mechanical Properties of Fluids' },
      { id: 'c11', title: 'Thermal Properties of Matter' },
      { id: 'c12', title: 'Thermodynamics' },
      { id: 'c13', title: 'Kinetic Theory' },
      { id: 'c14', title: 'Oscillations' },
      { id: 'c15', title: 'Waves' }
    ],
    "Maths": [
      { id: 'c1', title: 'Sets' },
      { id: 'c2', title: 'Relations and Functions' },
      { id: 'c3', title: 'Trigonometric Functions' },
      { id: 'c4', title: 'Principle of Mathematical Induction' },
      { id: 'c5', title: 'Complex Numbers and Quadratic Equations' },
      { id: 'c6', title: 'Linear Inequalities' },
      { id: 'c7', title: 'Permutations and Combinations' },
      { id: 'c8', title: 'Binomial Theorem' },
      { id: 'c9', title: 'Sequences and Series' },
      { id: 'c10', title: 'Straight Lines' },
      { id: 'c11', title: 'Conic Sections' },
      { id: 'c12', title: 'Introduction to Three Dimensional Geometry' },
      { id: 'c13', title: 'Limits and Derivatives' },
      { id: 'c14', title: 'Mathematical Reasoning' },
      { id: 'c15', title: 'Statistics' },
      { id: 'c16', title: 'Probability' }
    ],
    "Chemistry": [
      { id: 'c1', title: 'Some Basic Concepts of Chemistry' },
      { id: 'c2', title: 'Structure of Atom' },
      { id: 'c3', title: 'Classification of Elements and Periodicity in Properties' },
      { id: 'c4', title: 'Chemical Bonding and Molecular Structure' },
      { id: 'c5', title: 'States of Matter' },
      { id: 'c6', title: 'Thermodynamics' },
      { id: 'c7', title: 'Equilibrium' },
      { id: 'c8', title: 'Redox Reactions' },
      { id: 'c9', title: 'Hydrogen' },
      { id: 'c10', title: 'The s-Block Elements' },
      { id: 'c11', title: 'The p-Block Elements' },
      { id: 'c12', title: 'Organic Chemistry - Some Basic Principles and Techniques' },
      { id: 'c13', title: 'Hydrocarbons' },
      { id: 'c14', title: 'Environmental Chemistry' }
    ],
    "Biology": [
      { id: 'c1', title: 'The Living World' },
      { id: 'c2', title: 'Biological Classification' },
      { id: 'c3', title: 'Plant Kingdom' },
      { id: 'c4', title: 'Animal Kingdom' },
      { id: 'c5', title: 'Morphology of Flowering Plants' },
      { id: 'c6', title: 'Anatomy of Flowering Plants' },
      { id: 'c7', title: 'Structural Organisation in Animals' },
      { id: 'c8', title: 'Cell: The Unit of Life' },
      { id: 'c9', title: 'Biomolecules' },
      { id: 'c10', title: 'Cell Cycle and Cell Division' },
      { id: 'c11', title: 'Transport in Plants' },
      { id: 'c12', title: 'Mineral Nutrition' },
      { id: 'c13', title: 'Photosynthesis in Higher Plants' },
      { id: 'c14', title: 'Respiration in Plants' },
      { id: 'c15', title: 'Plant Growth and Development' },
      { id: 'c16', title: 'Digestion and Absorption' },
      { id: 'c17', title: 'Breathing and Exchange of Gases' },
      { id: 'c18', title: 'Body Fluids and Circulation' }
    ],
    "English": [
      { id: 'c1', title: 'English Chapter 1' },
      { id: 'c2', title: 'English Chapter 2' },
      { id: 'c3', title: 'English Chapter 3' },
      { id: 'c4', title: 'English Chapter 4' },
      { id: 'c5', title: 'English Chapter 5' },
      { id: 'c6', title: 'English Chapter 6' },
      { id: 'c7', title: 'English Chapter 7' },
      { id: 'c8', title: 'English Chapter 8' },
      { id: 'c9', title: 'English Chapter 9' },
      { id: 'c10', title: 'English Chapter 10' },
      { id: 'c11', title: 'English Chapter 11' },
      { id: 'c12', title: 'English Chapter 12' }
    ],
    "Business Studies": [
      { id: 'c1', title: 'Business Studies Chapter 1' },
      { id: 'c2', title: 'Business Studies Chapter 2' },
      { id: 'c3', title: 'Business Studies Chapter 3' },
      { id: 'c4', title: 'Business Studies Chapter 4' },
      { id: 'c5', title: 'Business Studies Chapter 5' },
      { id: 'c6', title: 'Business Studies Chapter 6' },
      { id: 'c7', title: 'Business Studies Chapter 7' },
      { id: 'c8', title: 'Business Studies Chapter 8' },
      { id: 'c9', title: 'Business Studies Chapter 9' },
      { id: 'c10', title: 'Business Studies Chapter 10' }
    ],
    "Economics": [
      { id: 'c1', title: 'Economics Chapter 1' },
      { id: 'c2', title: 'Economics Chapter 2' },
      { id: 'c3', title: 'Economics Chapter 3' },
      { id: 'c4', title: 'Economics Chapter 4' },
      { id: 'c5', title: 'Economics Chapter 5' },
      { id: 'c6', title: 'Economics Chapter 6' },
      { id: 'c7', title: 'Economics Chapter 7' },
      { id: 'c8', title: 'Economics Chapter 8' },
      { id: 'c9', title: 'Economics Chapter 9' },
      { id: 'c10', title: 'Economics Chapter 10' }
    ],
    "Accountancy": [
      { id: 'c1', title: 'Accountancy Chapter 1' },
      { id: 'c2', title: 'Accountancy Chapter 2' },
      { id: 'c3', title: 'Accountancy Chapter 3' },
      { id: 'c4', title: 'Accountancy Chapter 4' },
      { id: 'c5', title: 'Accountancy Chapter 5' },
      { id: 'c6', title: 'Accountancy Chapter 6' },
      { id: 'c7', title: 'Accountancy Chapter 7' },
      { id: 'c8', title: 'Accountancy Chapter 8' },
      { id: 'c9', title: 'Accountancy Chapter 9' },
      { id: 'c10', title: 'Accountancy Chapter 10' }
    ],
    "History": [
      { id: 'c1', title: 'History Chapter 1' },
      { id: 'c2', title: 'History Chapter 2' },
      { id: 'c3', title: 'History Chapter 3' },
      { id: 'c4', title: 'History Chapter 4' },
      { id: 'c5', title: 'History Chapter 5' },
      { id: 'c6', title: 'History Chapter 6' },
      { id: 'c7', title: 'History Chapter 7' },
      { id: 'c8', title: 'History Chapter 8' },
      { id: 'c9', title: 'History Chapter 9' },
      { id: 'c10', title: 'History Chapter 10' },
      { id: 'c11', title: 'History Chapter 11' }
    ],
    "Geography": [
      { id: 'c1', title: 'Geography Chapter 1' },
      { id: 'c2', title: 'Geography Chapter 2' },
      { id: 'c3', title: 'Geography Chapter 3' },
      { id: 'c4', title: 'Geography Chapter 4' },
      { id: 'c5', title: 'Geography Chapter 5' },
      { id: 'c6', title: 'Geography Chapter 6' },
      { id: 'c7', title: 'Geography Chapter 7' },
      { id: 'c8', title: 'Geography Chapter 8' },
      { id: 'c9', title: 'Geography Chapter 9' },
      { id: 'c10', title: 'Geography Chapter 10' },
      { id: 'c11', title: 'Geography Chapter 11' },
      { id: 'c12', title: 'Geography Chapter 12' }
    ],
    "Political Science": [
      { id: 'c1', title: 'Political Science Chapter 1' },
      { id: 'c2', title: 'Political Science Chapter 2' },
      { id: 'c3', title: 'Political Science Chapter 3' },
      { id: 'c4', title: 'Political Science Chapter 4' },
      { id: 'c5', title: 'Political Science Chapter 5' },
      { id: 'c6', title: 'Political Science Chapter 6' },
      { id: 'c7', title: 'Political Science Chapter 7' },
      { id: 'c8', title: 'Political Science Chapter 8' },
      { id: 'c9', title: 'Political Science Chapter 9' },
      { id: 'c10', title: 'Political Science Chapter 10' }
    ]
  },
  "Class 10": {
    "Maths": [
      { id: 'c1', title: 'Real Numbers' },
      { id: 'c2', title: 'Polynomials' },
      { id: 'c3', title: 'Pair of Linear Equations in Two Variables' },
      { id: 'c4', title: 'Quadratic Equations' },
      { id: 'c5', title: 'Arithmetic Progressions' },
      { id: 'c6', title: 'Triangles' },
      { id: 'c7', title: 'Coordinate Geometry' },
      { id: 'c8', title: 'Introduction to Trigonometry' },
      { id: 'c9', title: 'Some Applications of Trigonometry' },
      { id: 'c10', title: 'Circles' },
      { id: 'c11', title: 'Constructions' },
      { id: 'c12', title: 'Areas Related to Circles' },
      { id: 'c13', title: 'Surface Areas and Volumes' },
      { id: 'c14', title: 'Statistics' },
      { id: 'c15', title: 'Probability' }
    ],
    "Science": [
      { id: 'c1', title: 'Chemical Reactions and Equations' },
      { id: 'c2', title: 'Acids, Bases and Salts' },
      { id: 'c3', title: 'Metals and Non-metals' },
      { id: 'c4', title: 'Carbon and Its Compounds' },
      { id: 'c5', title: 'Periodic Classification of Elements' },
      { id: 'c6', title: 'Life Processes' },
      { id: 'c7', title: 'Control and Coordination' },
      { id: 'c8', title: 'How do Organisms Reproduce?' },
      { id: 'c9', title: 'Heredity and Evolution' },
      { id: 'c10', title: 'Light – Reflection and Refraction' },
      { id: 'c11', title: 'The Human Eye and the Colourful World' },
      { id: 'c12', title: 'Electricity' },
      { id: 'c13', title: 'Magnetic Effects of Electric Current' },
      { id: 'c14', title: 'Sources of Energy' },
      { id: 'c15', title: 'Our Environment' },
      { id: 'c16', title: 'Sustainable Management of Natural Resources' }
    ],
    "English": [
      { id: 'c1', title: 'English Chapter 1' },
      { id: 'c2', title: 'English Chapter 2' },
      { id: 'c3', title: 'English Chapter 3' },
      { id: 'c4', title: 'English Chapter 4' },
      { id: 'c5', title: 'English Chapter 5' },
      { id: 'c6', title: 'English Chapter 6' },
      { id: 'c7', title: 'English Chapter 7' },
      { id: 'c8', title: 'English Chapter 8' },
      { id: 'c9', title: 'English Chapter 9' },
      { id: 'c10', title: 'English Chapter 10' },
      { id: 'c11', title: 'English Chapter 11' },
      { id: 'c12', title: 'English Chapter 12' },
      { id: 'c13', title: 'English Chapter 13' },
      { id: 'c14', title: 'English Chapter 14' },
      { id: 'c15', title: 'English Chapter 15' }
    ],
    "Social Science": [
      { id: 'c1', title: 'Social Science Chapter 1' },
      { id: 'c2', title: 'Social Science Chapter 2' },
      { id: 'c3', title: 'Social Science Chapter 3' },
      { id: 'c4', title: 'Social Science Chapter 4' },
      { id: 'c5', title: 'Social Science Chapter 5' },
      { id: 'c6', title: 'Social Science Chapter 6' },
      { id: 'c7', title: 'Social Science Chapter 7' },
      { id: 'c8', title: 'Social Science Chapter 8' },
      { id: 'c9', title: 'Social Science Chapter 9' },
      { id: 'c10', title: 'Social Science Chapter 10' },
      { id: 'c11', title: 'Social Science Chapter 11' },
      { id: 'c12', title: 'Social Science Chapter 12' },
      { id: 'c13', title: 'Social Science Chapter 13' },
      { id: 'c14', title: 'Social Science Chapter 14' },
      { id: 'c15', title: 'Social Science Chapter 15' }
    ]
  },
  "Class 9": {
    "Maths": [
      { id: 'c1', title: 'Number Systems' },
      { id: 'c2', title: 'Polynomials' },
      { id: 'c3', title: 'Coordinate Geometry' },
      { id: 'c4', title: 'Linear Equations in Two Variables' },
      { id: 'c5', title: 'Introduction to Euclid\'s Geometry' },
      { id: 'c6', title: 'Lines and Angles' },
      { id: 'c7', title: 'Triangles' },
      { id: 'c8', title: 'Quadrilaterals' },
      { id: 'c9', title: 'Areas of Parallelograms and Triangles' },
      { id: 'c10', title: 'Circles' },
      { id: 'c11', title: 'Constructions' },
      { id: 'c12', title: 'Heron\'s Formula' },
      { id: 'c13', title: 'Surface Areas and Volumes' },
      { id: 'c14', title: 'Statistics' },
      { id: 'c15', title: 'Probability' }
    ],
    "Science": [
      { id: 'c1', title: 'Matter in Our Surroundings' },
      { id: 'c2', title: 'Is Matter Around Us Pure' },
      { id: 'c3', title: 'Atoms and Molecules' },
      { id: 'c4', title: 'Structure of the Atom' },
      { id: 'c5', title: 'The Fundamental Unit of Life' },
      { id: 'c6', title: 'Tissues' },
      { id: 'c7', title: 'Diversity in Living Organisms' },
      { id: 'c8', title: 'Motion' },
      { id: 'c9', title: 'Force and Laws of Motion' },
      { id: 'c10', title: 'Gravitation' },
      { id: 'c11', title: 'Work and Energy' },
      { id: 'c12', title: 'Sound' },
      { id: 'c13', title: 'Why Do We Fall Ill' },
      { id: 'c14', title: 'Natural Resources' },
      { id: 'c15', title: 'Improvement in Food Resources' }
    ],
    "English": [
      { id: 'c1', title: 'English Chapter 1' },
      { id: 'c2', title: 'English Chapter 2' },
      { id: 'c3', title: 'English Chapter 3' },
      { id: 'c4', title: 'English Chapter 4' },
      { id: 'c5', title: 'English Chapter 5' },
      { id: 'c6', title: 'English Chapter 6' },
      { id: 'c7', title: 'English Chapter 7' },
      { id: 'c8', title: 'English Chapter 8' },
      { id: 'c9', title: 'English Chapter 9' },
      { id: 'c10', title: 'English Chapter 10' },
      { id: 'c11', title: 'English Chapter 11' },
      { id: 'c12', title: 'English Chapter 12' },
      { id: 'c13', title: 'English Chapter 13' },
      { id: 'c14', title: 'English Chapter 14' },
      { id: 'c15', title: 'English Chapter 15' }
    ],
    "Social Science": [
      { id: 'c1', title: 'Social Science Chapter 1' },
      { id: 'c2', title: 'Social Science Chapter 2' },
      { id: 'c3', title: 'Social Science Chapter 3' },
      { id: 'c4', title: 'Social Science Chapter 4' },
      { id: 'c5', title: 'Social Science Chapter 5' },
      { id: 'c6', title: 'Social Science Chapter 6' },
      { id: 'c7', title: 'Social Science Chapter 7' },
      { id: 'c8', title: 'Social Science Chapter 8' },
      { id: 'c9', title: 'Social Science Chapter 9' },
      { id: 'c10', title: 'Social Science Chapter 10' },
      { id: 'c11', title: 'Social Science Chapter 11' },
      { id: 'c12', title: 'Social Science Chapter 12' },
      { id: 'c13', title: 'Social Science Chapter 13' },
      { id: 'c14', title: 'Social Science Chapter 14' },
      { id: 'c15', title: 'Social Science Chapter 15' }
    ]
  },
  "Class 8": {
    "Maths": [
      { id: 'c1', title: 'Rational Numbers' },
      { id: 'c2', title: 'Linear Equations in One Variable' },
      { id: 'c3', title: 'Understanding Quadrilaterals' },
      { id: 'c4', title: 'Practical Geometry' },
      { id: 'c5', title: 'Data Handling' },
      { id: 'c6', title: 'Squares and Square Roots' },
      { id: 'c7', title: 'Cubes and Cube Roots' },
      { id: 'c8', title: 'Comparing Quantities' },
      { id: 'c9', title: 'Algebraic Expressions and Identities' },
      { id: 'c10', title: 'Visualising Solid Shapes' },
      { id: 'c11', title: 'Mensuration' },
      { id: 'c12', title: 'Exponents and Powers' },
      { id: 'c13', title: 'Direct and Inverse Proportions' },
      { id: 'c14', title: 'Factorisation' },
      { id: 'c15', title: 'Introduction to Graphs' },
      { id: 'c16', title: 'Playing with Numbers' }
    ],
    "Science": [
      { id: 'c1', title: 'Crop Production and Management' },
      { id: 'c2', title: 'Microorganisms: Friend and Foe' },
      { id: 'c3', title: 'Synthetic Fibres and Plastics' },
      { id: 'c4', title: 'Materials: Metals and Non-Metals' },
      { id: 'c5', title: 'Coal and Petroleum' },
      { id: 'c6', title: 'Combustion and Flame' },
      { id: 'c7', title: 'Conservation of Plants and Animals' },
      { id: 'c8', title: 'Cell - Structure and Functions' },
      { id: 'c9', title: 'Reproduction in Animals' },
      { id: 'c10', title: 'Reaching the Age of Adolescence' },
      { id: 'c11', title: 'Force and Pressure' },
      { id: 'c12', title: 'Friction' },
      { id: 'c13', title: 'Sound' },
      { id: 'c14', title: 'Chemical Effects of Electric Current' },
      { id: 'c15', title: 'Some Natural Phenomena' },
      { id: 'c16', title: 'Light' },
      { id: 'c17', title: 'Stars and the Solar System' },
      { id: 'c18', title: 'Pollution of Air and Water' }
    ],
    "English": [
      { id: 'c1', title: 'English Chapter 1' },
      { id: 'c2', title: 'English Chapter 2' },
      { id: 'c3', title: 'English Chapter 3' },
      { id: 'c4', title: 'English Chapter 4' },
      { id: 'c5', title: 'English Chapter 5' },
      { id: 'c6', title: 'English Chapter 6' },
      { id: 'c7', title: 'English Chapter 7' },
      { id: 'c8', title: 'English Chapter 8' },
      { id: 'c9', title: 'English Chapter 9' },
      { id: 'c10', title: 'English Chapter 10' }
    ],
    "Social Science": [
      { id: 'c1', title: 'Social Science Chapter 1' },
      { id: 'c2', title: 'Social Science Chapter 2' },
      { id: 'c3', title: 'Social Science Chapter 3' },
      { id: 'c4', title: 'Social Science Chapter 4' },
      { id: 'c5', title: 'Social Science Chapter 5' },
      { id: 'c6', title: 'Social Science Chapter 6' },
      { id: 'c7', title: 'Social Science Chapter 7' },
      { id: 'c8', title: 'Social Science Chapter 8' },
      { id: 'c9', title: 'Social Science Chapter 9' },
      { id: 'c10', title: 'Social Science Chapter 10' },
      { id: 'c11', title: 'Social Science Chapter 11' },
      { id: 'c12', title: 'Social Science Chapter 12' }
    ]
  },
  "Class 7": {
    "Maths": [
      { id: 'c1', title: 'Integers' },
      { id: 'c2', title: 'Fractions and Decimals' },
      { id: 'c3', title: 'Data Handling' },
      { id: 'c4', title: 'Simple Equations' },
      { id: 'c5', title: 'Lines and Angles' },
      { id: 'c6', title: 'The Triangle and its Properties' },
      { id: 'c7', title: 'Congruence of Triangles' },
      { id: 'c8', title: 'Comparing Quantities' },
      { id: 'c9', title: 'Rational Numbers' },
      { id: 'c10', title: 'Practical Geometry' },
      { id: 'c11', title: 'Perimeter and Area' },
      { id: 'c12', title: 'Algebraic Expressions' },
      { id: 'c13', title: 'Exponents and Powers' },
      { id: 'c14', title: 'Symmetry' },
      { id: 'c15', title: 'Visualising Solid Shapes' }
    ],
    "Science": [
      { id: 'c1', title: 'Nutrition in Plants' },
      { id: 'c2', title: 'Nutrition in Animals' },
      { id: 'c3', title: 'Fibre to Fabric' },
      { id: 'c4', title: 'Heat' },
      { id: 'c5', title: 'Acids, Bases and Salts' },
      { id: 'c6', title: 'Physical and Chemical Changes' },
      { id: 'c7', title: 'Weather, Climate and Adaptations of Animals to Climate' },
      { id: 'c8', title: 'Winds, Storms and Cyclones' },
      { id: 'c9', title: 'Soil' },
      { id: 'c10', title: 'Respiration in Organisms' },
      { id: 'c11', title: 'Transportation in Animals and Plants' },
      { id: 'c12', title: 'Reproduction in Plants' },
      { id: 'c13', title: 'Motion and Time' },
      { id: 'c14', title: 'Electric Current and its Effects' },
      { id: 'c15', title: 'Light' },
      { id: 'c16', title: 'Water: A Precious Resource' },
      { id: 'c17', title: 'Forests: Our Lifeline' },
      { id: 'c18', title: 'Wastewater Story' }
    ],
    "English": [
      { id: 'c1', title: 'English Chapter 1' },
      { id: 'c2', title: 'English Chapter 2' },
      { id: 'c3', title: 'English Chapter 3' },
      { id: 'c4', title: 'English Chapter 4' },
      { id: 'c5', title: 'English Chapter 5' },
      { id: 'c6', title: 'English Chapter 6' },
      { id: 'c7', title: 'English Chapter 7' },
      { id: 'c8', title: 'English Chapter 8' },
      { id: 'c9', title: 'English Chapter 9' },
      { id: 'c10', title: 'English Chapter 10' }
    ],
    "Social Science": [
      { id: 'c1', title: 'Social Science Chapter 1' },
      { id: 'c2', title: 'Social Science Chapter 2' },
      { id: 'c3', title: 'Social Science Chapter 3' },
      { id: 'c4', title: 'Social Science Chapter 4' },
      { id: 'c5', title: 'Social Science Chapter 5' },
      { id: 'c6', title: 'Social Science Chapter 6' },
      { id: 'c7', title: 'Social Science Chapter 7' },
      { id: 'c8', title: 'Social Science Chapter 8' },
      { id: 'c9', title: 'Social Science Chapter 9' },
      { id: 'c10', title: 'Social Science Chapter 10' }
    ]
  },
  "Class 6": {
    "Maths": [
      { id: 'c1', title: 'Knowing Our Numbers' },
      { id: 'c2', title: 'Whole Numbers' },
      { id: 'c3', title: 'Playing with Numbers' },
      { id: 'c4', title: 'Basic Geometrical Ideas' },
      { id: 'c5', title: 'Understanding Elementary Shapes' },
      { id: 'c6', title: 'Integers' },
      { id: 'c7', title: 'Fractions' },
      { id: 'c8', title: 'Decimals' },
      { id: 'c9', title: 'Data Handling' },
      { id: 'c10', title: 'Mensuration' },
      { id: 'c11', title: 'Algebra' },
      { id: 'c12', title: 'Ratio and Proportion' },
      { id: 'c13', title: 'Symmetry' },
      { id: 'c14', title: 'Practical Geometry' }
    ],
    "Science": [
      { id: 'c1', title: 'Food: Where Does It Come From?' },
      { id: 'c2', title: 'Components of Food' },
      { id: 'c3', title: 'Fibre to Fabric' },
      { id: 'c4', title: 'Sorting Materials Into Groups' },
      { id: 'c5', title: 'Separation of Substances' },
      { id: 'c6', title: 'Changes Around Us' },
      { id: 'c7', title: 'Getting to Know Plants' },
      { id: 'c8', title: 'Body Movements' },
      { id: 'c9', title: 'The Living Organisms and Their Surroundings' },
      { id: 'c10', title: 'Motion and Measurement of Distances' },
      { id: 'c11', title: 'Light, Shadows and Reflections' },
      { id: 'c12', title: 'Electricity and Circuits' },
      { id: 'c13', title: 'Fun with Magnets' },
      { id: 'c14', title: 'Water' },
      { id: 'c15', title: 'Air Around Us' },
      { id: 'c16', title: 'Garbage In, Garbage Out' }
    ],
    "English": [
      { id: 'c1', title: 'English Chapter 1' },
      { id: 'c2', title: 'English Chapter 2' },
      { id: 'c3', title: 'English Chapter 3' },
      { id: 'c4', title: 'English Chapter 4' },
      { id: 'c5', title: 'English Chapter 5' },
      { id: 'c6', title: 'English Chapter 6' },
      { id: 'c7', title: 'English Chapter 7' },
      { id: 'c8', title: 'English Chapter 8' },
      { id: 'c9', title: 'English Chapter 9' },
      { id: 'c10', title: 'English Chapter 10' }
    ],
    "Social Science": [
      { id: 'c1', title: 'Social Science Chapter 1' },
      { id: 'c2', title: 'Social Science Chapter 2' },
      { id: 'c3', title: 'Social Science Chapter 3' },
      { id: 'c4', title: 'Social Science Chapter 4' },
      { id: 'c5', title: 'Social Science Chapter 5' },
      { id: 'c6', title: 'Social Science Chapter 6' },
      { id: 'c7', title: 'Social Science Chapter 7' },
      { id: 'c8', title: 'Social Science Chapter 8' },
      { id: 'c9', title: 'Social Science Chapter 9' },
      { id: 'c10', title: 'Social Science Chapter 10' }
    ]
  },
  "Class 5": {
    "Maths": [
      { id: 'c1', title: 'The Fish Tale' },
      { id: 'c2', title: 'Shapes and Angles' },
      { id: 'c3', title: 'How Many Squares?' },
      { id: 'c4', title: 'Parts and Wholes' },
      { id: 'c5', title: 'Does it Look the Same?' },
      { id: 'c6', title: 'Be My Multiple, I\'ll be Your Factor' },
      { id: 'c7', title: 'Can You See the Pattern?' },
      { id: 'c8', title: 'Mapping Your Way' },
      { id: 'c9', title: 'Boxes and Sketches' },
      { id: 'c10', title: 'Tenths and Hundredths' },
      { id: 'c11', title: 'Area and its Boundary' },
      { id: 'c12', title: 'Smart Charts' },
      { id: 'c13', title: 'Ways to Multiply and Divide' },
      { id: 'c14', title: 'How Big? How Heavy?' }
    ],
    "EVS": [
      { id: 'c1', title: 'Super Senses' },
      { id: 'c2', title: 'A Snake Charmer\'s Story' },
      { id: 'c3', title: 'From Tasting to Digesting' },
      { id: 'c4', title: 'Mangoes Round the Year' },
      { id: 'c5', title: 'Seeds and Seeds' },
      { id: 'c6', title: 'Every Drop Counts' },
      { id: 'c7', title: 'Experiments with Water' },
      { id: 'c8', title: 'A Treat for Mosquitoes' },
      { id: 'c9', title: 'Up You Go!' },
      { id: 'c10', title: 'Walls Tell Stories' },
      { id: 'c11', title: 'Sunita in Space' },
      { id: 'c12', title: 'What if it Finishes...?' },
      { id: 'c13', title: 'A Shelter so High!' },
      { id: 'c14', title: 'When the Earth Shook!' },
      { id: 'c15', title: 'Blow Hot, Blow Cold' },
      { id: 'c16', title: 'Who will do this Work?' },
      { id: 'c17', title: 'Across the Wall' },
      { id: 'c18', title: 'No Place for Us?' },
      { id: 'c19', title: 'A Seed tells a Farmer\'s Story' },
      { id: 'c20', title: 'Whose Forests?' },
      { id: 'c21', title: 'Like Father, Like Daughter' },
      { id: 'c22', title: 'On the Move Again' }
    ],
    "English": [
      { id: 'c1', title: 'English Chapter 1' },
      { id: 'c2', title: 'English Chapter 2' },
      { id: 'c3', title: 'English Chapter 3' },
      { id: 'c4', title: 'English Chapter 4' },
      { id: 'c5', title: 'English Chapter 5' },
      { id: 'c6', title: 'English Chapter 6' },
      { id: 'c7', title: 'English Chapter 7' },
      { id: 'c8', title: 'English Chapter 8' },
      { id: 'c9', title: 'English Chapter 9' },
      { id: 'c10', title: 'English Chapter 10' }
    ]
  },
  "Class 4": {
    "Maths": [
      { id: 'c1', title: 'Building with Bricks' },
      { id: 'c2', title: 'Long and Short' },
      { id: 'c3', title: 'A Trip to Bhopal' },
      { id: 'c4', title: 'Tick-Tick-Tick' },
      { id: 'c5', title: 'The Way The World Looks' },
      { id: 'c6', title: 'The Junk Seller' },
      { id: 'c7', title: 'Jugs and Mugs' },
      { id: 'c8', title: 'Carts and Wheels' },
      { id: 'c9', title: 'Halves and Quarters' },
      { id: 'c10', title: 'Play with Patterns' },
      { id: 'c11', title: 'Tables and Shares' },
      { id: 'c12', title: 'How Heavy? How Light?' },
      { id: 'c13', title: 'A Field and Fences' },
      { id: 'c14', title: 'Smart Charts' }
    ],
    "EVS": [
      { id: 'c1', title: 'Going to School' },
      { id: 'c2', title: 'Ear to Ear' },
      { id: 'c3', title: 'A Day with Nandu' },
      { id: 'c4', title: 'The Story of Amrita' },
      { id: 'c5', title: 'Anita and the Honeybees' },
      { id: 'c6', title: 'Omana\'s Journey' },
      { id: 'c7', title: 'From the Window' },
      { id: 'c8', title: 'Reaching Grandmother\'s House' },
      { id: 'c9', title: 'Changing Families' },
      { id: 'c10', title: 'Hu Tu Tu, Hu Tu Tu' },
      { id: 'c11', title: 'The Valley of Flowers' },
      { id: 'c12', title: 'Changing Times' },
      { id: 'c13', title: 'A River\'s Tale' },
      { id: 'c14', title: 'Basva\'s Farm' },
      { id: 'c15', title: 'From Market to Home' },
      { id: 'c16', title: 'A Busy Month' },
      { id: 'c17', title: 'Nandita in Mumbai' },
      { id: 'c18', title: 'Too Much Water, Too Little Water' },
      { id: 'c19', title: 'Abdul in the Garden' },
      { id: 'c20', title: 'Eating Together' },
      { id: 'c21', title: 'Food and Fun' },
      { id: 'c22', title: 'The World in my Home' },
      { id: 'c23', title: 'Pochampalli' },
      { id: 'c24', title: 'Home and Abroad' },
      { id: 'c25', title: 'Spicy Riddles' },
      { id: 'c26', title: 'Defence Officer: Wahida' },
      { id: 'c27', title: 'Chuskit Goes to School' }
    ],
    "English": [
      { id: 'c1', title: 'English Chapter 1' },
      { id: 'c2', title: 'English Chapter 2' },
      { id: 'c3', title: 'English Chapter 3' },
      { id: 'c4', title: 'English Chapter 4' },
      { id: 'c5', title: 'English Chapter 5' },
      { id: 'c6', title: 'English Chapter 6' },
      { id: 'c7', title: 'English Chapter 7' },
      { id: 'c8', title: 'English Chapter 8' },
      { id: 'c9', title: 'English Chapter 9' },
      { id: 'c10', title: 'English Chapter 10' }
    ]
  },
  "Class 3": {
    "Maths": [
      { id: 'c1', title: 'Where to Look From' },
      { id: 'c2', title: 'Fun with Numbers' },
      { id: 'c3', title: 'Give and Take' },
      { id: 'c4', title: 'Long and Short' },
      { id: 'c5', title: 'Shapes and Designs' },
      { id: 'c6', title: 'Fun with Give and Take' },
      { id: 'c7', title: 'Time Goes On' },
      { id: 'c8', title: 'Who is Heavier?' },
      { id: 'c9', title: 'How Many Times?' },
      { id: 'c10', title: 'Play with Patterns' },
      { id: 'c11', title: 'Jugs and Mugs' },
      { id: 'c12', title: 'Can We Share?' },
      { id: 'c13', title: 'Smart Charts!' },
      { id: 'c14', title: 'Rupees and Paise' }
    ],
    "EVS": [
      { id: 'c1', title: 'Poonam\'s Day Out' },
      { id: 'c2', title: 'The Plant Fairy' },
      { id: 'c3', title: 'Water O\' Water!' },
      { id: 'c4', title: 'Our First School' },
      { id: 'c5', title: 'Chhotu\'s House' },
      { id: 'c6', title: 'Foods We Eat' },
      { id: 'c7', title: 'Saying without Speaking' },
      { id: 'c8', title: 'Flying High' },
      { id: 'c9', title: 'It\'s Raining' },
      { id: 'c10', title: 'What is Cooking' },
      { id: 'c11', title: 'From Here to There' },
      { id: 'c12', title: 'Work We Do' },
      { id: 'c13', title: 'Sharing Our Feelings' },
      { id: 'c14', title: 'The Story of Food' },
      { id: 'c15', title: 'Making Pots' },
      { id: 'c16', title: 'Games We Play' },
      { id: 'c17', title: 'Here comes a Letter' },
      { id: 'c18', title: 'A House Like This' },
      { id: 'c19', title: 'Our Friends - Animals' },
      { id: 'c20', title: 'Drop by Drop' },
      { id: 'c21', title: 'Families can be Different' },
      { id: 'c22', title: 'Left-Right' },
      { id: 'c23', title: 'A Beautiful Cloth' },
      { id: 'c24', title: 'Web of Life' }
    ],
    "English": [
      { id: 'c1', title: 'English Chapter 1' },
      { id: 'c2', title: 'English Chapter 2' },
      { id: 'c3', title: 'English Chapter 3' },
      { id: 'c4', title: 'English Chapter 4' },
      { id: 'c5', title: 'English Chapter 5' },
      { id: 'c6', title: 'English Chapter 6' },
      { id: 'c7', title: 'English Chapter 7' },
      { id: 'c8', title: 'English Chapter 8' },
      { id: 'c9', title: 'English Chapter 9' },
      { id: 'c10', title: 'English Chapter 10' }
    ]
  },
  "Class 2": {
    "Maths": [
      { id: 'c1', title: 'What is Long, What is Round?' },
      { id: 'c2', title: 'Counting in Groups' },
      { id: 'c3', title: 'How Much Can You Carry?' },
      { id: 'c4', title: 'Counting in Tens' },
      { id: 'c5', title: 'Patterns' },
      { id: 'c6', title: 'Footprints' },
      { id: 'c7', title: 'Jugs and Mugs' },
      { id: 'c8', title: 'Tens and Ones' },
      { id: 'c9', title: 'My Funday' },
      { id: 'c10', title: 'Add Our Points' },
      { id: 'c11', title: 'Lines and Lines' },
      { id: 'c12', title: 'Give and Take' },
      { id: 'c13', title: 'The Longest Step' },
      { id: 'c14', title: 'Birds Come, Birds Go' },
      { id: 'c15', title: 'How Many Ponytails?' }
    ],
    "English": [
      { id: 'c1', title: 'First Day at School' },
      { id: 'c2', title: 'Haldi\'s Adventure' },
      { id: 'c3', title: 'I am Lucky!' },
      { id: 'c4', title: 'I Want' },
      { id: 'c5', title: 'A Smile' },
      { id: 'c6', title: 'The Wind and the Sun' },
      { id: 'c7', title: 'Rain' },
      { id: 'c8', title: 'Storm in the Garden' },
      { id: 'c9', title: 'Zoo Manners' },
      { id: 'c10', title: 'Funny Bunny' },
      { id: 'c11', title: 'Mr. Nobody' },
      { id: 'c12', title: 'Curlylocks and the Three Bears' },
      { id: 'c13', title: 'On My Blackboard I can Draw' },
      { id: 'c14', title: 'Make it Shorter' },
      { id: 'c15', title: 'I am the Music Man' },
      { id: 'c16', title: 'The Mumbai Musicians' },
      { id: 'c17', title: 'Granny Granny Please Comb my Hair' },
      { id: 'c18', title: 'The Magic Porridge Pot' },
      { id: 'c19', title: 'Strange Talk' },
      { id: 'c20', title: 'The Grasshopper and the Ant' }
    ]
  },
  "Class 1": {
    "Maths": [
      { id: 'c1', title: 'Shapes and Space' },
      { id: 'c2', title: 'Numbers from One to Nine' },
      { id: 'c3', title: 'Addition' },
      { id: 'c4', title: 'Subtraction' },
      { id: 'c5', title: 'Numbers from Ten to Twenty' },
      { id: 'c6', title: 'Time' },
      { id: 'c7', title: 'Measurement' },
      { id: 'c8', title: 'Numbers from Twenty-one to Fifty' },
      { id: 'c9', title: 'Data Handling' },
      { id: 'c10', title: 'Patterns' },
      { id: 'c11', title: 'Numbers' },
      { id: 'c12', title: 'Money' },
      { id: 'c13', title: 'How Many' }
    ],
    "English": [
      { id: 'c1', title: 'A Happy Child' },
      { id: 'c2', title: 'Three Little Pigs' },
      { id: 'c3', title: 'After a Bath' },
      { id: 'c4', title: 'The Bubble, the Straw and the Shoe' },
      { id: 'c5', title: 'One Little Kitten' },
      { id: 'c6', title: 'Lalu and Peelu' },
      { id: 'c7', title: 'Once I Saw a Little Bird' },
      { id: 'c8', title: 'Mittu and the Yellow Mango' },
      { id: 'c9', title: 'Merry-Go-Round' },
      { id: 'c10', title: 'Circle' },
      { id: 'c11', title: 'If I Were an Apple' },
      { id: 'c12', title: 'Our Tree' },
      { id: 'c13', title: 'A Kite' },
      { id: 'c14', title: 'Sundari' },
      { id: 'c15', title: 'A Little Turtle' },
      { id: 'c16', title: 'The Tiger and the Mosquito' },
      { id: 'c17', title: 'Clouds' },
      { id: 'c18', title: 'Anandi\'s Rainbow' },
      { id: 'c19', title: 'Flying-Man' },
      { id: 'c20', title: 'The Tailor and his Friend' }
    ]
  },
  "NCERT Books": {
    "All Books PDF": [
      { id: 'c1', title: 'Class 12 Books' },
      { id: 'c2', title: 'Class 11 Books' },
      { id: 'c3', title: 'Class 10 Books' },
      { id: 'c4', title: 'Class 9 Books' },
      { id: 'c5', title: 'Class 8 Books' },
      { id: 'c6', title: 'Class 7 Books' },
      { id: 'c7', title: 'Class 6 Books' },
      { id: 'c8', title: 'Class 5 Books' },
      { id: 'c9', title: 'Class 4 Books' },
      { id: 'c10', title: 'Class 3 Books' },
      { id: 'c11', title: 'Class 2 Books' },
      { id: 'c12', title: 'Class 1 Books' }
    ]
  },
  "NCERT Exempler": {
    "Maths Exemplar": [
      { id: 'c1', title: 'Class 12 Maths Exemplar' },
      { id: 'c2', title: 'Class 11 Maths Exemplar' },
      { id: 'c3', title: 'Class 10 Maths Exemplar' },
      { id: 'c4', title: 'Class 9 Maths Exemplar' }
    ],
    "Science Exemplar": [
      { id: 'c1', title: 'Class 12 Physics Exemplar' },
      { id: 'c2', title: 'Class 12 Chemistry Exemplar' },
      { id: 'c3', title: 'Class 12 Biology Exemplar' },
      { id: 'c4', title: 'Class 10 Science Exemplar' },
      { id: 'c5', title: 'Class 9 Science Exemplar' }
    ]
  }
};
    fs.writeFileSync('temp_chapters.json', JSON.stringify(chaptersData));
    